Adding mobs
Nesaak/Voltskiya pull request #2
Opened 2020-05-30 02:56 UTC by amp7368

added the 2 custom mobs I've made. There were no commands or anything much to change to move this over

2020-05-30 14:57 UTC, harrisonglp requested changes

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaAI.java
> +        synchronized (thylaWasHitSync) {
Do you ever access this stuff off the main thread anyway?

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaAI.java
> +    private static boolean rayTrace(@NotNull World world, @NotNull Vector spot1, @NotNull Vector spot2) {
May want to use World#rayTrace unless you have a reason not to.

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaSpawnOrHitListener.java
> +    public void onCreatureSpawn(CreatureSpawnEvent event) {
You need to add `if (event.isCancelled()) return;` to avoid running if event is cancelled.

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaSpawnOrHitListener.java
> +    public void onEntityHit(EntityDamageEvent event){
I would do the same here as what I said above.

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/utils/RotateCustomModel.java
> +        Bukkit.getScheduler().scheduleSyncDelayedTask(plugin, () -> RotateCustomModel.rotate(entities, center, plugin), 2);
Why delay this?

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/better_spider_spawn/BetterSpiderSpawn.java
> +    public void onCreatureSpawn(CreatureSpawnEvent event) {
Don't run fix spawn checks if cancelled

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/better_spider_spawn/BetterSpiderSpwnMain.java
> +public class BetterSpiderSpwnMain {
Is this a typo? Should it be "BetterSpiderSpawnMain"?

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/araneo/WebProjectile.java
> +            if (projectile.isDead()) {
Check isValid() rather than isDead()

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaAI.java
> +        if (thyla.isDead()) {
Check isValid, not isDead

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/araneo/AraneoAI.java
> +        if (araneo.isDead()) return;
check isValid, not isDead

2020-05-30 14:57 UTC, harrisonglp commented on src/main/java/com/voltskiya/core/custom_mobs/araneo/AraneoSpawnListener.java
> +    public void onAraneoSpawn(CreatureSpawnEvent event) {
return if cancelled

2020-05-30 17:38 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaAI.java
> +        synchronized (thylaWasHitSync) {
No, I don't. It would never be the case that thylaWasHitSync would be useful. But I figure it's best to stay in the habit of keeping things synchronized if they have the chance to be broken if it's not synchronized. It's more for good programming habits than efficient code

2020-05-30 17:52 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaAI.java
> +    private static boolean rayTrace(@NotNull World world, @NotNull Vector spot1, @NotNull Vector spot2) {
I have no reason not so so we will. ^-^

2020-05-30 18:26 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaSpawnOrHitListener.java
> +    public void onCreatureSpawn(CreatureSpawnEvent event) {
added ignoreCancelled = true

2020-05-30 18:27 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaSpawnOrHitListener.java
> +    public void onEntityHit(EntityDamageEvent event){
fixed

2020-05-30 18:29 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/utils/RotateCustomModel.java
> +        Bukkit.getScheduler().scheduleSyncDelayedTask(plugin, () -> RotateCustomModel.rotate(entities, center, plugin), 2);
this makes it spin forever. I delay because it's an infinite loop. this was mainly for testing. it will be changed when I implement custom models.

2020-05-30 18:30 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/better_spider_spawn/BetterSpiderSpwnMain.java
> +public class BetterSpiderSpwnMain {
yes it was a typo

2020-05-30 18:33 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/araneo/WebProjectile.java
> +            if (projectile.isDead()) {
ok

2020-05-30 18:34 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/thyla/ThylaAI.java
> +        if (thyla.isDead()) {
done

2020-05-30 18:34 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/araneo/AraneoAI.java
> +        if (araneo.isDead()) return;
done

2020-05-30 18:35 UTC, amp7368 commented on src/main/java/com/voltskiya/core/custom_mobs/araneo/AraneoSpawnListener.java
> +    public void onAraneoSpawn(CreatureSpawnEvent event) {
ignoreCancelled=true

2020-06-01 13:13 UTC, harrisonglp approved these changes

2020-06-01 16:38 UTC, merged